{% set name = "nested-dask" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nested_dask-{{ version }}.tar.gz
  sha256: 199c7bbf86f2555ae3a924ccb81a584191232a22536bbba4b7adcdeb839cd7cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - nested-pandas >=0.3.8,<0.4.0
    - numpy
    - pyarrow
    - dask-core >=2025.1.0

test:
  imports:
    - nested_dask
  commands:
    - pip check
    - pytest tests/nested_dask/test_accessor.py
  requires:
    - pip
    - pytest
    - requests
    - aiohttp
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/lincc-frameworks/nested-dask
  summary: A dask extension of nested-pandas.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dougbrn
    - hombit
